name: projetonovo
description: A new Flutter project.
publish_to: 'none'

version: 1.0.13

environment:
  sdk: '>=3.0.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  pdf: ^3.6.5
  share_plus: ^10.0.0
  auto_size_text: ^3.0.0
  provider: ^6.1.2
  intl: ^0.19.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  crypto: ^3.0.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.4
  firebase_core: ^2.31.1
  firebase_messaging: ^14.4.2
  flutter_native_timezone:
    path: Pacotes/flutter_native_timezone-master
  percent_indicator: ^4.2.3
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  path: ^1.9.0
  quickalert: ^1.1.0
  simple_animations: ^5.0.2
  supercharged: ^2.1.1
  lottie: ^3.1.2
  table_calendar: ^3.1.1
  flutter_datetime_picker: ^1.5.1
  permission_handler: ^11.3.1
  pdfx: ^2.6.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  flutter_typeahead: ^5.2.0
  money_formatter: ^0.0.6
  currency_formatter: ^2.2.1
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  firebase_analytics: ^10.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  meta: ^1.14.0
  rive_common: ^0.4.9
  device_info_plus: ^9.1.2
  js: ^0.6.7
  photo_view: ^0.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/imagens/avatar.png
    - assets/imagens/avatar2.jpg
    - assets/imagens/pdf.png
    - assets/imagens/capa.png
    - assets/imagens/entradacapa.png
    - assets/imagens/logo_dti.jpeg
    - assets/imagens/whatsapp.png
    - assets/imagens/fotocapa.jpeg
    - assets/imagens/help.png
    - assets/imagens/previa.png
    - assets/imagens/logo_pmrr.png
    - assets/imagens/pmrrr.png
    - assets/imagens/logo-contracheque.jpeg
    - assets/imagens/dti.jpeg
    - assets/contracheque.pdf
    - assets/contracheque2.pdf
    - assets/lottie/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
